### ISSUE TITLE
UnboundLocalError at vincenty distance

### ISSUE THREAD

**Issue by kataev** [geopy/geopy#242] opened 2017-04-27 16:05 UTC
```
import sys
print(sys.version_info)
print(geopy.__version__)
geopy.distance.vincenty((np.NaN, np.NaN), (1,1))

sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
1.11.0
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-87-a808b291b901> in <module>()
      2 print(sys.version_info)
      3 print(geopy.__version__)
----> 4 geopy.distance.vincenty((np.NaN, np.NaN), (1,1))

/Users/pk/miniconda3/lib/python3.6/site-packages/geopy/distance.py in __init__(self, *args, **kwargs)
    320         self.iterations = kwargs.pop('iterations', 20)
    321         major, minor, f = self.ELLIPSOID # pylint: disable=W0612
--> 322         super(vincenty, self).__init__(*args, **kwargs)
    323 
    324     def set_ellipsoid(self, ellipsoid):

/Users/pk/miniconda3/lib/python3.6/site-packages/geopy/distance.py in __init__(self, *args, **kwargs)
    113         elif len(args) > 1:
    114             for a, b in util.pairwise(args):
--> 115                 kilometers += self.measure(a, b)
    116 
    117         kilometers += units.kilometers(**kwargs)

/Users/pk/miniconda3/lib/python3.6/site-packages/geopy/distance.py in measure(self, a, b)
    412             raise ValueError("Vincenty formula failed to converge!")
    413 
--> 414         u_sq = cos_sq_alpha * (major ** 2 - minor ** 2) / minor ** 2
    415 
    416         A = 1 + u_sq / 16384. * (

UnboundLocalError: local variable 'cos_sq_alpha' referenced before assignment
```

**Comment by cffk** [comment] 2017-04-28 09:50
Perhaps it's worth revisiting pull request #144.  Surely geopy should
offer a method for computing geodesic distances that "just works".

**Comment by cffk** [comment] 2017-05-06 11:40
The same error can be triggered without NaNs with
~~~
geopy.distance.vincenty((0,-180),(0,180))
~~~

**Comment by KostyaEsmukov** [comment] 2018-03-23 14:58
Closing this, as I'm unable to reproduce the issue. Added the tests in 0ea5e8d and they currently pass. Feel free to reopen if anyone finds another test which fails.

**Closed by KostyaEsmukov** 2018-03-23 14:58 UTC

**Comment by cffk** [comment] 2018-03-23 18:02
@KostyaEsmukov You fixed this with commit 15ebe153b.

**Comment by KostyaEsmukov** [comment] 2018-03-24 08:04
> Gag... this fixed a different bug --- sorry.

Actually, I think they're related, so I guess you're right: 15ebe15 has probably fixed this as well. 

Before 15ebe15 [the `while` loop condition](https://github.com/geopy/geopy/blob/15ebe153bd9cfbd6d503195ab85d1d6e91df302a/geopy/distance.py#L388) had just `abs(lambda_lng - lambda_prime) > 10e-12`, which would turn to False when `lambda_lng` is NaN. Thus the loop would be never entered and hence the unbound variable exception.

Now that the unbound variable exception is fixed, all calculations with NaNs simply return NaNs, which is basically expected, but probably is not a desired behaviour for someone calculating distances to quietly get NaNs instead of explicit exceptions. As I said in #245, I'd be glad if someone would make a PR to raise ValueError on bad input.

**Comment by cffk** [comment] 2018-03-27 13:48
FYI, here's how the geographiclib package handles bad values.

* All arguments are expected to be numeric.  However this is not
  explicitly checked.  Instead the user will get some complaint from the
  bowels of the code.

* Exact range reduction is done on longitudes and azimuths.  This means
  that any finite values are OK.  Inf becomes NaN.

* Distances are unrestricted.

* Latitudes must lie in [-90,90].  Latitudes outside this range are
  **silently** turned into NaNs.

* NaNs and Infs progagate through the code as expected.  (Actually this
  isn't quite true since with python `math.sin(float("inf"))` ->
  `math domain error`.  I'll fix this.)

The expectation is that wacky values should be handled by some outer
user-facing layer.

**Comment by KostyaEsmukov** [comment] 2018-04-01 15:00
@cffk Thank you, this list is helpful. I opened #272 PR which issues warnings for some of these cases. Could you take a look, please?
  
  

> Latitudes must lie in [-90,90]. Latitudes outside this range are silently turned into NaNs.

Coordinates are wrapped in `Point`, which does latitude and longitude normalization ([by modulo](https://github.com/geopy/geopy/blob/4c8cbf056175b27d87242c2b96c0ca0178c91907/geopy/point.py#L134)), so the underlying distance computation algorithm receives latitudes in range [-90; 90] (for finite values).

**Comment by cffk** [comment] 2018-04-01 22:12
There are two problematic aspects to the normalizations done by Point.

* Using % to do the modulo calculations potentially loses 1 bit of
  accuracy.  E.g., `longitude = 180.000000000000028` becomes `-180`
  instead of `-179.999999999999972`.  GeographicLib uses `math.fmod`
  instead, although this is slightly verbose:

      def AngNormalize(x):
        """reduce angle to (-180,180]"""

        y = math.fmod(x, 360)
        # On Windows 32-bit with python 2.7, math.fmod(-0.0, 360) = +0.0
        # This fixes this bug.
        y = x if x == 0 else y
        return (y + 360 if y <= -180 else
                (y if y <= 180 else y - 360))
      AngNormalize = staticmethod(AngNormalize)

* `latitude = 90.001` which most people would think of as being in the
  vicinity of the north pole becomes `latitude = -89.999`, close to the
  south pole.  I think this would come as a shock to most people.  There
  are various alternatives for latitude = 90.001, longitude = 10:

  1.  raise an exception;
  2. `(NaN, 10)`, i.e., silently mark it as bogus;
  3. `(90, 10)`, i.e., "correct" the latitude;
  4. `(89,999, -170)`, i.e., switch to the antimeridian (but the azimuth
    should also be fixed in this case).

  I suggest i or ii.

**Comment by KostyaEsmukov** [comment] 2018-04-02 08:42
> Using % to do the modulo calculations potentially loses 1 bit of accuracy.

This is a good point. I'm going to create an issue for that to leave it for someone else to implement, as it doesn't seem urgent to me.

> `latitude = 90.001` which most people would think of as being in the
vicinity of the north pole becomes `latitude = -89.999`, close to the
south pole.

Yeah, I reasoned about this before and decided to start with warnings for now (but somehow I missed in #272 that Point constructor needs some warnings too; I'm going to add them). Then we may start raising exceptions instead of warnings in the next versions (at least for the latitude case, which normalization seems really harmful).

Regarding ii: eventually I would like the distance to raise exceptions when a meaningful result cannot be computed (due to divergence or NaNs).

Another problem here is that Point instances are currently mutable. It means that coordinates normalization/validation should also be done in class descriptors for the coordinate attributes. But using descriptors instead of simple attributes slows down attribute access by ~6-10 times in my environment, which I consider unwanted.
