### ISSUE TITLE
Occasional KeyError on ArcGIS().reverse()

### ISSUE THREAD

**Issue by filwaitman** [geopy/geopy#219] opened 2016-09-16 14:35 UTC
Hi there!

First, many thanks for this project. This is really helping me!  =]

Given some coordinates I'm facing a `KeyError` when calling `ArcGIS().reverse()`. Take a look:

```
>>> import geopy
>>> print geopy.__version__
'1.11.0'
>>> geopy.geocoders.arcgis.ArcGIS().reverse(query=(40.7046944961, -73.9784406834))
# ...
KeyError: 'y'

>>> import sys
>>> print sys.version
2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]
```

Do you guys know what I'm doing wrong? Or is it an issue on `ArcGIS` side?

Thanks!

**Comment by jmb** [comment] 2016-10-17 11:24
For some reason ArcGIS is returning a `location` with a `paths` entry instead of the expected `y` and `x` co-ordinates:
```
{
    u'location': {
        u'paths': [[[-73.97898603909321, 40.70218038045718], [-73.97855648251084, 40.703761325817055]], [[-73.97855648251084, 40.703761325817055], [-73.97937573991021, 40.70390303520505]], [[-73.97855648251084, 40.703761325817055], [-73.97832620475535, 40.704571726379676]]],
        u'spatialReference': {u'wkid': 4326, u'latestWkid': 4326}
    },
    u'address': {...}
}
```

This is not mentioned in the [API docs](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm) so I'm not sure how this should be handled!

**Comment by filwaitman** [comment] 2016-10-17 14:41
Ouch.

Well, this is just a suggestion: maybe geopy should assert returned dict from ArcGIS has the `location.x` and `location.y` inner keys and raise a `ArcGISMisbehavedExpection` otherwise. In fact, Since it's not documented I don't think you guys should even try to infer `location.x` and `location.y` here - this would be way too dangerous.

What do you think?

**Comment by KostyaEsmukov** [comment] 2018-04-02 08:52
Looks like #227 might solve this (`candidates` object is used instead of `location` there).

**Comment by KostyaEsmukov** [comment] 2018-05-06 14:53
Actually, #227 didn't touch the reverse method code, so it must be unrelated to this issue.

However I'm unable to reproduce it. The code in the issue description works without errors for me. Perhaps the issue has been fixed on the ArcGIS side?

Anyway, I'm closing this. Feel free to reopen if the issue persists.

**Closed by KostyaEsmukov** 2018-05-06 14:53 UTC
Labels: has open PR
