### ISSUE TITLE
reverse error

### ISSUE THREAD

**Issue by coolkit-carl** [geopy/geopy#369] opened 2019-09-02 07:53 UTC
```
def getAddress(longitude, latitude):
    gps = Nominatim(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36')
    location = gps.reverse(f"{longitude}, {latitude}")
    return location.address
```
But I tried to run the code. It reported an error.
The specific errors are as follows:

```
Traceback (most recent call last):
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 956, in send
    self.connect()
  File "D:\Environment\Miniconda3\envs\test\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "D:\Environment\Miniconda3\envs\test\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "D:\Environment\Miniconda3\envs\test\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "D:\Environment\Miniconda3\envs\test\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Environment\Miniconda3\envs\test\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\Environment\Miniconda3\envs\test\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1039: The handshake operation timed out>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Environment\Miniconda3\envs\test\lib\site-packages\geopy\geocoders\osm.py", line 449, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "D:\Environment\Miniconda3\envs\test\lib\site-packages\geopy\geocoders\base.py", line 378, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out
```

I need your help，thanks

**Comment by KostyaEsmukov** [comment] 2019-09-02 18:25
As stated in [CONTRIBUTING.md](https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#reporting-issues), the issue tracker is not intended for support, so I'm going to close this issue.

You shouldn't be using a user agent of a web browser, I believe this doesn't comply with the Nominatim TOS, which implies that user agent should identify an application, whereas your Python script is definitely not a Google Chrome browser.

`socket.timeout: _ssl.c:1039: The handshake operation timed out` might be caused by network connectivity issues. Try opening https://nominatim.openstreetmap.org/ with your web browser first. If that doesn't work, then the problem is not in geopy. If it does, then you might have faced the Windows-specific quirk of the trusted certificates, see #212

**Closed by KostyaEsmukov** 2019-09-02 18:25 UTC
