### ISSUE TITLE
distance.distance() ValueError: math domain error

### ISSUE THREAD

**Issue by agdhruv** [geopy/geopy#466] opened 2021-01-31 20:02 UTC
Here's an isolated example (coordinates taken from [SF dataset](https://crawdad.org/epfl/mobility/20090224/)) :

```python
from geopy import distance

distance.distance([37.757540000000006, -122.47018], [37.75754, -122.470177])
```
Throws: `ValueError: ValueError: math domain error`

<details><summary>Stack Trace</summary>
<p>

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geopy/distance.py", line 389, in __init__
    super(geodesic, self).__init__(*args, **kwargs)
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geopy/distance.py", line 164, in __init__
    kilometers += self.measure(a, b)
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geopy/distance.py", line 419, in measure
    s12 = self.geod.Inverse(lat1, lon1, lat2, lon2,
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geographiclib/geodesic.py", line 1035, in Inverse
    a12, s12, salp1,calp1, salp2,calp2, m12, M12, M21, S12 = self._GenInverse(
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geographiclib/geodesic.py", line 880, in _GenInverse
    eps, domg12, dv) = self._Lambda12(
  File "/mnt/redacted-path/env/lib/python3.8/site-packages/geographiclib/geodesic.py", line 658, in _Lambda12
    calp2 = (math.sqrt(Math.sq(calp1 * cbet1) +
ValueError: math domain error
```

</p>
</details>

**Comment by cffk** [comment] 2021-01-31 20:43
Thanks for this report.  I can reproduce this problem (on Linux not MacOS).  I'm investigating...

**Comment by cffk** [comment] 2021-01-31 22:14
The problem is that `math.hypot` behaves badly in python3.  Here's the illustration (based on your example):
```python
import math
x = 0.6102683302836215;
y1 = 0.7906090004346522
y2 = y1 + 1e-16
da = y2 - y1
db = math.hypot(x, y2)           - math.hypot(x, y1)
dc = math.sqrt(x**2 + y2**2)     - math.sqrt(x**2 + y1**2)
dd = y2*math.sqrt(1 + (x/y2)**2) - y1*math.sqrt(1 + (x/y1)**2)
print([da,db,dc,dd])
```

By rights, the printed result should be 4 non-negative numbers.  In fact, python2 and python3 give
```python
[1.1e-16,  1.1e-16, 1.1e-16, -1.1e-16]
[1.1e-16, -1.1e-16, 1.1e-16, -1.1e-16]
```
respectively.  This shows that python3 is implementing `math.hypot` along the lines of the calculation of `dd`, while python2 managed to do a little better.  I'll report this as a python bug; but I'm not sure how much traction this will get.  In the meantime, a fix is change `Math.norm` as follows:
```patch
diff --git a/python/geographiclib/geomath.py b/python/geographiclib/geomath.py
index daf0fb30..69938267 100644
--- a/python/geographiclib/geomath.py
+++ b/python/geographiclib/geomath.py
@@ -84,7 +84,7 @@ class Math(object):
 
   def norm(x, y):
     """Private: Normalize a two-vector."""
-    r = math.hypot(x, y)
+    r = math.sqrt(Math.sq(x) + Math.sq(y))
     return x/r, y/r
   norm = staticmethod(norm)
 
```

**Comment by cffk** [comment] 2021-01-31 23:51
Evidently, this bug is fixed in python 3.10.

**Comment by cffk** [comment] 2021-02-01 15:12
The bad versions of python are 3.8 and 3.9.  So a tailored patch is
```patch
diff --git a/python/geographiclib/geomath.py b/python/geographiclib/geomath.py
index daf0fb30..1da422e7 100644
--- a/python/geographiclib/geomath.py
+++ b/python/geographiclib/geomath.py
@@ -84,7 +84,9 @@ class Math(object):
 
   def norm(x, y):
     """Private: Normalize a two-vector."""
-    r = math.hypot(x, y)
+    r = (math.sqrt(Math.sq(x) + Math.sq(y)) # hypot is inaccurate for 3.[89]
+         if (3, 8) <= sys.version_info < (3, 10)
+         else math.hypot(x, y))
     return x/r, y/r
   norm = staticmethod(norm)
 
```

**Comment by agdhruv** [comment] 2021-02-19 07:56
Hi! Sorry for missing your comments. Geat working on debugging this! I'm not in a hurry for a fix either, so feel free to follow your existing release timelines. Thanks!

**Comment by KostyaEsmukov** [comment] 2021-03-20 20:11
Thank you, Charles.

I'm going to keep this open, in order to pin the new geographiclib version once it will be released.

**Closed** 2022-08-07 09:10 UTC
