### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on Windows Server 2012

### ISSUE THREAD

**Issue by Cetino** [geopy/geopy#212] opened 2016-08-26 14:34 UTC
Hello,

i get this strange error on Windows Server 2012... what can i do ?

  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 171, in _ca
ll_geocoder    raise GeocoderServiceError(message)geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:590)>

**Comment by Cetino** [comment] 2016-08-26 15:54
ok i solved it. The trick was to open google once with Internet Explorer.....

**Comment by jjmmolina** [comment] 2017-10-02 14:54
I have this error in the same OS.:
geopy.exc.GeocoderServiceError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

What can I do??

**Comment by KostyaEsmukov** [comment] 2018-03-23 14:37
This is a Windows-specific issue. Since 2.7.9/3.4 Python (and urllib, which is used by geopy) uses trusted certs directly from Windows Certificate Stores. So in order to fix this – make sure that the failing geocoder's certificate is trusted by Internet Explorer.

I'm closing this, but feel free to add details on this issue. Also linking #181 which was intended to workaround this by disabling tls verification completely.

Some refs:
- https://github.com/pypa/pip/issues/2510 (mentions that required intermediate certificate might be downloaded with browser, as @Cetino suggested)
- https://www.python.org/dev/peps/pep-0543/
- https://bugs.python.org/issue28547

If anyone comes across this later and finds out that the trick with opening geocoder's URL with IE actually helps, please let us know (or, even better, open a PR to document this).

**Closed by KostyaEsmukov** 2018-03-23 14:37 UTC

**Comment by dpsspatial** [comment] 2018-04-09 18:05
What is the URL for the Google geocoder I should be opening in Internet Explorer? 

I'm having this issue when the script is run through Windows Task Scheduler - for some reason if I run it manually, I don't get the error.

**Comment by KostyaEsmukov** [comment] 2018-04-09 18:17
It's https://maps.googleapis.com 

https://github.com/geopy/geopy/blob/d29244dcbe31e8a0773cd45e752462fba4579657/geopy/geocoders/googlev3.py#L41

What error do you get? It doesn't look like a certificates issue if a manual run succeeds.

**Comment by KostyaEsmukov** [comment] 2018-04-10 19:37
I'm not that experienced with Windows, but I guess that it might be due to the different user accounts: the one used by Windows Task Scheduler might not have an access to the required certificates from the Certificate Stores. In that case choosing your user account in the Task Scheduler record should fix this issue. But again: that's just a guess.

**Comment by KostyaEsmukov** [comment] 2018-05-11 06:16
#291 has added support for passing custom `ssl_context`, which might be helpful there. For example, a custom CA bundle can be specified, or TLS verification can be disabled completely.
