### ISSUE TITLE
Photon implementation raises exceptions.IndexError when location text actually lists multiple locations

### ISSUE THREAD

**Issue by paulborza** [geopy/geopy#161] opened 2015-10-23 16:48 UTC
```
'job_location': u'San Francisco, Singapore, Glasgow',
 'job_location_type': 'Site',
 'job_title': u'Internship: Computer Science',
 'job_type': 'Internship',
 'job_url': u'http://spire.com/careers/?gh_jid=19705',
 'startup_id': 'spire'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 62, in _process_chain
    return process_chain(self.methods[methodname], obj, *args)
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 65, in process_chain
    d.callback(input)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 383, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "test.py", line 174, in process_item
    location = geolocator.geocode(item['job_location'])
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/photon.py", line 133, in geocode
    exactly_one
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/photon.py", line 202, in _parse_json
    return cls.parse_resource(resources['features'][0])
exceptions.IndexError: list index out of range
```

**Comment by mthh** [comment] 2015-11-26 11:52
Hi,
I made a pull request (#153)  some time ago about the photon implementation. I guess in your case it don't raise an `IndexError` because many locations where returned but because no location was returned. I modified my previous PR and after that i'm unable to reproduce the error (so if the PR #153 is merged it should resolved this).
```python
In [1]: from geopy import Photon

In [2]: phton = Photon()

In [3]: phton.geocode('San Francisco, Singapore, Glasgow') # Shouldn't find a result

In [4]: phton.geocode('Glasgow') # Should output one answer
Out[4]: Location(Glasgow, G, Scotland, United Kingdom, (55.861147, -4.2499891, 0.0))

In [5]: phton.geocode('Glasgow', exactly_one=False) # Should output many
Out[5]:
[Location(Glasgow, G, Scotland, United Kingdom, (55.861147, -4.2499891, 0.0)),
 Location(Glasgow, Kentucky, United States of America, (36.9958841, -85.9119215, 0.0)),
 Location(University of Glasgow, University Avenue, G, University Avenue, Glasgow, Scotland, United Kingdom, (55.8723241, -4.289206856798055, 0.0)),
 Location(Port Glasgow, Scotland, United Kingdom, (55.9360653, -4.6980937, 0.0)),
 Location(Glasgow Central, Argyle Street, G, Argyle Street, Glasgow, Scotland, United Kingdom, (55.858634699999996, -4.258247177551022, 0.0)),
 Location(Glasgow International Airport, Walkinshaw Road, Walkinshaw Road, Inchinnan, Scotland, United Kingdom, (55.8719444, -4.4330556, 0.0)),
(...)]
```
Cheers

**Comment by KostyaEsmukov** [comment] 2018-04-01 18:07
2bb4a920 should have fixed this

**Closed by KostyaEsmukov** 2018-04-01 18:07 UTC
