### ISSUE TITLE
Specifiy results limit

### ISSUE THREAD

**Issue by Serphentas** [geopy/geopy#280] opened 2018-04-08 20:43 UTC
Currently, one can only specify if only one or more results should be returned using the `exactly_one` parameter. It would be nice to have the ability to specify an integer limit (ex. `count`) so that when `exactly_one` is false, no more than `count` results are returned.

This is really just to preserve resources on the geocoding server. For instance, if using Nominatim, that would set the `limit` parameter sent to it.

**Comment by KostyaEsmukov** [comment] 2018-04-09 03:01
Indeed, this is an issue with Nominatim. However, this is an exact duplicate of #170, so I'm closing this.

Are you interested in providing a PR? That would be great!

**Closed by KostyaEsmukov** 2018-04-09 03:01 UTC

**Comment by Serphentas** [comment] 2018-04-09 07:09
Sorry, I didn't see #170.

I am definitely interested in a PR. I'll check out what's been done over there and try to get something going on. Thanks !
