### ISSUE TITLE
Google maps reverse geocoding does not return the English location names even when then language option is set to en

### ISSUE THREAD

**Issue by vgiotsas** [geopy/geopy#231] opened 2016-11-29 02:21 UTC
In the documentation it says that the the [reverse](http://geopy.readthedocs.io/en/latest/#geopy.geocoders.GoogleV3.reverse) geocoding function for the Google Maps V3 API will return the results in the language of the the `language` attribute. However, setting this attribute to `en` has no impact, the city names are returned in the local language which makes parsing very difficult.

**Comment by svalee** [comment] 2018-04-10 20:30
Hey @vgiotsas ! I tried to reproduce this issue, but it doesn't seem like it's working for me. Could you please look and confirm if it's still a problem?
Here's my python interactive session:

>>> from geopy.geocoders import GoogleV3
>>> google = GoogleV3('my-key')
>>> google.reverse((39.997522, 124.363728), language='en')
[Location(Ya Lu Jiang Da Dao, Zhenxing Qu, Dandong Shi, Liaoning Sheng, China, (39.9999081, 124.3654066, 0.0)), Location(Zhenxing, Dandong, Liaoning, China, (40.105193, 124.3602631, 0.0)), Location(Dandong, Liaoning, China, (40.000787, 124.35445, 0.0)), Location(North Korea, (40.339852, 127.510093, 0.0)), Location(Liaoning, China, (41.9436543, 122.5290376, 0.0))]
>>> google.reverse((35.865434, 14.487888), language='en')
[Location(Sqaq Il Fdal Tal Hadid, Ħal Luqa, Malta, (35.8653767, 14.4891403, 0.0)), Location(Luqa, Malta, (35.8582865, 14.4868883, 0.0)), Location(Malta, (35.937496, 14.375416, 0.0))]
>>> google.reverse((58.816565, 130.146215), language='en')
[Location(Sakha Republic, Russia, 678915, (57.49755940000001, 129.9219959, 0.0)), Location(Aldanskiy Ulus, Sakha Republic, Russia, (58.82398829999999, 128.6769586, 0.0)), Location(Sakha Republic, Russia, (66.7613451, 124.123753, 0.0)), Location(Russia, (61.52401, 105.318756, 0.0))]

I think, the only possible way to get result in a local language is if no english translation were provided by google, but I think it's rarely happening if it is.

**Comment by KostyaEsmukov** [comment] 2018-07-07 19:53
Perhaps that was a temporary issue on Google's side? To me it looks like the doc is aligned with the behaviour (as shown in the example provided by @svalee above), so I'm closing this.

Another reason I can think of is that some places might be not translated to some languages in Google, then the local name might be returned. In that case the doc might be updated like "The language in which to return results **(if available)**", but without an actual example of a query showing the issue I wouldn't do such a change.

**Closed by KostyaEsmukov** 2018-07-07 19:53 UTC
Labels: help wanted

**Comment by carlosamaya1** [comment] 2024-04-17 19:20
Please reopen this issue, I have a valid example for this lat and longs in Poland look:

?latlng=52.517567,21.702429&language=en&key

If you run this you have the response in polish and english, example state in polish:

![image](https://github.com/geopy/geopy/assets/149541762/74e73f2e-02e7-41bc-a498-040e20d988fd)

and in the same response you have this state name in english:

![image](https://github.com/geopy/geopy/assets/149541762/c9970389-2f1b-45e6-9bd3-54828495a7aa)

And thanks to this I messed up a lot of data in my database
