### ISSUE TITLE
Nominatim - Possible Database Compromise

### ISSUE THREAD

**Issue by dmchaledev** [geopy/geopy#322] opened 2018-08-27 19:28 UTC
Looks like someone may have compromised your DB and changed all permutations of the United States to return USA, Creedon Republic. This confused the hell out of me this morning and appears to have happened around 05:00 UTC on 8/26. I don't see mention of it anywhere in the issues here or on your site at https://nominatim.openstreetmap.org. I've included a Python 2 snippet below for reproducing the issue with common permutations of the US 

from geopy.geocoders import Nominatim

language = 'en'
geolocator = Nominatim(user_agent="MobRev")
region_list = ["US",
			   "USA",
			   "United States"]

for region in region_list:
    try:
        if region != '':
            location = geolocator.geocode(query=region, language=language)
            time.sleep(1)
            country = location.raw['display_name'].split(',')[-1].lstrip()
            print('Region:', region)
            print('Location:', location.address)
            print('Country:', country)
    except:
    	print('Not found')

**Comment by mtmail** [comment] 2018-08-27 19:55
Duplicate of https://github.com/openstreetmap/Nominatim/issues/1158 Can be closed here. OpenStreetMap data itself is fine, the public nominatim.openstreetmap.org server instance needs an admin to delete the object.

**Closed** 2018-08-28 04:08 UTC
