### ISSUE TITLE
Service not available on using geolocator.reverse

### ISSUE THREAD

**Issue by MohanaRC** [geopy/geopy#259] opened 2017-12-19 11:12 UTC
I am using 
geolocator = Nominatim()
location = geolocator.reverse(str(gtr_y)+","+str(gtr_x))
to generate the address of 15 locations using the latitude and longitude values inside a loop.
There was no issue until now, but I kept getting the following error today,
File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/osm.py", line 248, in reverse
  self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 165, in _call_geocoder
raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

**Comment by WilfriedBl** [comment] 2017-12-19 17:17
Seems to be a problem with Nominatim today. Trying to access http://nominatim.openstreetmap.org on a browser also shows: 
"Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

**Comment by RazrSaw** [comment] 2018-02-07 11:07
>on Dec 19, 2017
...
Service still unavailable

**Comment by ritwik95** [comment] 2018-03-16 07:25
Still not working for me

**Comment by KostyaEsmukov** [comment] 2018-03-16 08:12
This has been fixed in `1.12.0`. I've just checked [the example in Readme](https://github.com/geopy/geopy/blob/6fb61717a4598f33e80b0f6d2ff771215f981fbf/README.rst#geocoding) and it works fine for me. Are you sure that you're using `1.12.0`?

It can be checked this way:
```
$ python
>>> from geopy.util import get_version
>>> get_version()
'1.12.0'
```

**Comment by ritwik95** [comment] 2018-03-16 09:17
Hi,

I am getting  '<urlopen error [Errno 65] No route to host>' error in most (I think more than 95%) of my reverse geocoding requests.

**Comment by KostyaEsmukov** [comment] 2018-03-16 10:19
Hmm, that's strange. I don't think that there were any changes in 1.12.0 that could've caused this.

Could you please try to install the previous version `1.11.0` to ensure that this error is not caused by your environment? If the error persists, then the cause is probably not in geopy itself.

I'd also note that `Nominatim` is not a good choice for a large number of requests for a short time. Their [usage policy](https://operations.osmfoundation.org/policies/nominatim/) requires to not exceed 1 query per second rate. If this is what you're trying to do, when it's probably better to switch to another service (or add delays if the amount of requests is not very large).

**Comment by ritwik95** [comment] 2018-03-16 10:27
Nominatim is itself down. Their website is also not opening. 

https://nominatim.openstreetmap.org/ 

I think the issue is from nominatim's end.

**Comment by KostyaEsmukov** [comment] 2018-03-17 16:59
The issue doesn't seem to be on geopy's side, so I'm closing this.

**Closed by KostyaEsmukov** 2018-03-17 16:59 UTC
