### ISSUE TITLE
Make Distance objects hashable

### ISSUE THREAD

**Issue by jachymb** [geopy/geopy#514] opened 2022-03-18 11:15 UTC
In my project I wanted to use a `Distance` instance as a dict key, but it's not possible because the `__hash__` method is not implented. I believe this should be easy to do - just return the `hash` of the underlying numeric representation.

**Comment by TomGoBravo** [comment] 2022-07-24 14:19
This looks like a duplicate of https://github.com/geopy/geopy/issues/485

**Comment by KostyaEsmukov** [comment] 2022-07-31 20:30
Closing as a duplicate of #485

**Closed by KostyaEsmukov** 2022-07-31 20:30 UTC
