### ISSUE TITLE
Proxies not being used in Nominatim?

### ISSUE THREAD

**Issue by octohedron** [geopy/geopy#263] opened 2018-02-17 00:24 UTC
Hello, seems like the proxies I'm passing to `Nominatim` are not being used?

```python
PROXIES = [
    {"http": "IP:PORT"},
    {"http": "IP:PORT"},
    ...
]
proxy = random.choice(PROXIES)
geolocator = Nominatim(proxies=proxy)
print(geolocator.proxies)  # Prints the proxy
```
I'm not sure why but it keeps throwing `429` too many requests, if I stop the script and manually call the same request with `curl`, using the same exact proxy it printed, it doesn't return `429`, which leads me to think the proxies are not being used or detected somehow?

**Comment by mtmail** [comment] 2018-03-12 11:48
Nominatim's 429 blocks generic user agents https://operations.osmfoundation.org/policies/nominatim/

So I'd say it's a duplicate of https://github.com/geopy/geopy/issues/262 and cURL isn't blocked.

**Closed** 2018-03-12 16:27 UTC
